import type { Metadata } from "next";
import {ReactNode} from "react";
import { Lato } from "next/font/google";
import localFont from "next/font/local";
import "@/styles/globals.scss";
import "@/styles/swipers.scss";
import Header from "@/components/widgets/header/header";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import clsx from "clsx";
import Providers from "./providers";
import { Footer } from "@/components/widgets/footer/footer";
import { MobileButtons } from "@/components/pages/home/mobile-buttons/mobile-buttons";
import { CommonService } from "@/services/common";
import { RequestSectionService } from "@/services/request";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700", "900"] });
const saar = localFont({
  src: "../fonts/SaarSPDemo.woff2",
  variable: "--font-saar-sp-demo",
});
const adderley = localFont({
  src: "../fonts/AdderleyBold.otf",
  variable: "--font-adderley",
});

export const metadata: Metadata = {
  title: "DALEE",
  description: "Generated by create next app",
};

gsap.registerPlugin(useGSAP, ScrollTrigger);

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const commonResponse = await CommonService.getAll();
  const requestSectionResponse = await RequestSectionService.getAll();

  return (
    <html lang="ru">
      <body
        suppressHydrationWarning={true}
        className={clsx(lato.className, saar.variable, adderley.variable)}>
        <Providers>
          <Header commonData={commonResponse.data.attributes} />
          {children}
          <MobileButtons
            requestSection={requestSectionResponse.data.attributes}
            commonData={commonResponse.data.attributes}
          />
          <Footer commonData={commonResponse.data.attributes} />
        </Providers>
      </body>
    </html>
  );
}
